#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_account?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL =false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver